; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[default_envs]
env_default = release

;
; ESP8266
;

[esp8266]
platform = espressif8266
board = esp8285
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_deps =
	knolleary/PubSubClient
	links2004/WebSockets
;GyverLibs/GyverHub
	https://github.com/GyverLibs/GyverHub.git
	GyverLibs/StringUtils
	GyverLibs/Pairs
	GyverLibs/GSON
	fastled/FastLED@^3.6.0
	gyverlibs/EncButton @ ^3.7.3

[debug]
monitor_filters = esp8266_exception_decoder, default
build_type = debug

[env:release]
extends = esp8266

[env:debug]
extends = esp8266, debug